version: '3'

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "4999:4999"
    environment:
      - USER_SERVICE_URL=http://localhost:5001   #UPDATE TO USER_SERVICE_URL=http://<INTERNAL_LB_IP_ADDRESS>:5001
      - AUTH_SERVICE_URL=http://localhost:5002   #UPDATE TO AUTH_SERVICE_URL=http://<INTERNAL_LB_IP_ADDRESS>:5001
      - TASK_SERVICE_URL=http://localhost:5003   #UPDATE TO TASK_SERVICE_URL=http://<INTERNAL_LB_IP_ADDRESS>:5001
    depends_on:
      - user_service
      - auth_service
      - task_service

  user_service:
    build: ./user_service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://user_service_user:yourpassword@database-1.c61cck4osj3q.us-east-1.rds.amazonaws.com:5432/user_db
      #- DATABASE_URL=postgresql://user_service_user:${USER_SERVICE_DB_PASSWORD}@database-1.c61cck4osj3q.us-east-1.rds.amazonaws.com:5432/user_db
    env_file:
      - .env
    restart: always

  auth_service:
    build: ./auth_service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://auth_service_user:yourpassword@database-1.c61cck4osj3q.us-east-1.rds.amazonaws.com:5432/auth_db
      #- DATABASE_URL=postgresql://auth_service_user:${AUTH_SERVICE_DB_PASSWORD}@database-1.c61cck4osj3q.us-east-1.rds.amazonaws.com:5432/auth_db
    env_file:
      - .env
    restart: always

  task_service:
    build: ./task_service
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://task_service_user:yourpassword@database-1.c61cck4osj3q.us-east-1.rds.amazonaws.com:5432/task_db
      #- DATABASE_URL=postgresql://auth_service_user:${AUTH_SERVICE_DB_PASSWORD}@database-1.c61cck4osj3q.us-east-1.rds.amazonaws.com:5432/auth_db
    env_file:
      - .env
    restart: always

networks:
  default:
    driver: bridge