version: '3'

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user_service:5001
      - AUTH_SERVICE_URL=http://auth_service:5002
      - TASK_SERVICE_URL=http://task_service:5003
    depends_on:
      - user_service
      - auth_service
      - task_service

  user_service:
    build: ./user_service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://user_service_user:${USER_SERVICE_DB_PASSWORD}@database-1.c61cck4osj3q.us-east-1.rds.amazonaws.com:5432/user_db
    env_file:
      - .env
    depends_on:
      - aws_rds
    restart: always

  auth_service:
    build: ./auth_service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://auth_service_user:${AUTH_SERVICE_DB_PASSWORD}@database-1.c61cck4osj3q.us-east-1.rds.amazonaws.com:5432/auth_db
    env_file:
      - .env
    depends_on:
      - aws_rds
    restart: always

  task_service:
    build: ./task_service
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://task_service_user:${TASK_SERVICE_DB_PASSWORD}@database-1.c61cck4osj3q.us-east-1.rds.amazonaws.com:5432/task_db
    env_file:
      - .env
    depends_on:
      - aws_rds
    restart: always

networks:
  default:
    driver: bridge